[theme]

# Primary accent for interactive elements
primaryColor = '#514bff'

# Background color for the main content area
backgroundColor = '#000000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#b9dcf1'

# Color used for almost all text
textColor = '#f2a7a0'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"